<?php

function unidades_a2_a4_por_codigo(string $codigo): array
{
    $mapa = [
        'en' => niveis_ingles(),
        'es' => niveis_espanhol(),
        'fr' => niveis_frances(),
        'it' => niveis_italiano(),
        'de' => niveis_alemao(),
    ];

    return $mapa[$codigo] ?? ['palavras' => [], 'unidades' => [], 'descricao' => null];
}

function niveis_ingles(): array
{
    return [
        'descricao' => 'Trilha QECR: do A1 ao C2, do cumprimento à precisão profissional.',
        'palavras' => [
            ['Yesterday', 'Ontem', 'I worked yesterday.', 'A2'],
            ['Already', 'Já', 'I have already eaten.', 'A2'],
            ['Because', 'Porque', 'I stayed home because it rained.', 'B1'],
            ['Although', 'Embora', 'Although I was tired, I went.', 'B1'],
            ['If', 'Se', 'If it rains, I will stay home.', 'B2'],
            ['Experience', 'Experiência', 'It was a great experience.', 'B2'],
        ],
        'unidades' => [
            [
                'titulo' => 'Ontem',
                'descricao' => 'Contar o que já aconteceu no passado simples.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Simple past',
                        'resumo' => 'worked, went, had, was/were',
                        'teoria' => "Passado de hábitos e fatos:\nI worked yesterday. She went to the market.\nwas / were · had · did / didn't\nPergunta: Did you go? What did you do?",
                        'exercicios' => [
                            m('Qual está no passado?', ['I go yesterday', 'I went yesterday', 'I going yesterday', 'I goes yesterday'], 'I went yesterday'),
                            t('Traduza: I worked yesterday', 'eu trabalhei ontem|trabalhei ontem'),
                            c('Complete: She _____ (not) go.', "didn't|did not"),
                            emp('Una.', [['went', 'foi'], ['had', 'teve'], ['was', 'era/estava'], ['did', 'fez (auxiliar)']]),
                            vf('"Did you go?" é a pergunta no passado simples.', true),
                            ordena('Monte:', 'What did you do yesterday'),
                            m('They were tired. usa:', ['was', 'were', 'is', 'are'], 'were'),
                            m('Forma correta:', ['Did she went?', 'Did she go?', 'She did went?', 'Went she?'], 'Did she go?'),
                        ],
                    ],
                    [
                        'titulo' => 'Contar o dia',
                        'resumo' => 'first, then, after that, finally',
                        'teoria' => "Para narrar: first · then · after that · finally\nIn the morning I… · In the afternoon… · At night…\nIt was a long day.",
                        'exercicios' => [
                            m('Qual liga a sequência?', ['first / then', 'hello / bye', 'left / right', 'yes / no'], 'first / then'),
                            t('Traduza: It was a long day', 'foi um dia longo|foi um longo dia|o dia foi longo'),
                            c('Complete: _____ that, I went home. (depois)', 'After'),
                            emp('Una.', [['morning', 'manhã'], ['afternoon', 'tarde'], ['night', 'noite'], ['finally', 'por fim']]),
                            vf('"Finally" fecha a sequência da história.', true),
                            ordena('Monte:', 'First I had breakfast'),
                            m('At night I slept. descreve:', ['o futuro', 'o fim do dia', 'um pedido', 'uma cor'], 'o fim do dia'),
                            m('After that significa:', ['antes disso', 'depois disso', 'em vez disso', 'apesar disso'], 'depois disso'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Planos',
                'descricao' => 'Falar do que vai acontecer: going to e will.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Going to',
                        'resumo' => 'planos já decididos',
                        'teoria' => "I'm going to travel in July.\nShe's going to study tonight.\nAre you going to come?\nUso: plano já pensado, evidência no presente.",
                        'exercicios' => [
                            m('Plano já decidido:', ["I'm going to travel", 'I traveling', 'I going travel', 'I will going'], "I'm going to travel"),
                            t('Traduza: I am going to study', 'vou estudar|eu vou estudar'),
                            c('Complete: She is _____ to cook.', 'going'),
                            emp('Una.', [['tonight', 'hoje à noite'], ['tomorrow', 'amanhã'], ['next week', 'semana que vem'], ['in July', 'em julho']]),
                            vf('"Are you going to come?" pergunta sobre um plano.', true),
                            ordena('Monte:', 'We are going to travel'),
                            m('Next week aponta para:', ['o passado', 'o futuro próximo', 'agora', 'nunca'], 'o futuro próximo'),
                            m('Negativa:', ["I'm not going to go", "I not going", "I don't going to", 'I no going'], "I'm not going to go"),
                        ],
                    ],
                    [
                        'titulo' => 'Will e convites',
                        'resumo' => 'will, maybe, would you like',
                        'teoria' => "I'll help you. (decisão na hora)\nMaybe I'll call later.\nWould you like to go out?\nI'd love to. / Sorry, I can't.",
                        'exercicios' => [
                            m('Decisão na hora:', ["I'll help you", 'I helping you', 'I going help', 'I helps you'], "I'll help you"),
                            t('Traduza: Would you like to go out?', 'voce gostaria de sair|você gostaria de sair|gostaria de sair'),
                            c("Complete: Sorry, I _____.", "can't|cannot"),
                            emp('Una.', [["I'll help", 'eu ajudo / vou ajudar'], ['maybe', 'talvez'], ["I'd love to", 'adoraria'], ["I can't", 'não posso']]),
                            vf('"Would you like" é um convite educado.', true),
                            ordena('Monte:', 'Would you like to go out'),
                            m("I'd love to. responde:", ['um convite', 'um preço', 'um nome', 'uma hora'], 'um convite'),
                            m('Maybe indica:', ['certeza total', 'possibilidade', 'passado', 'ordem'], 'possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Opiniões',
                'descricao' => 'Comparar, concordar e explicar por quê.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'I think…',
                        'resumo' => 'I think, because, I agree',
                        'teoria' => "I think this film is great.\nI don't think so.\nI agree / I disagree.\nbecause · that's why\nIn my opinion…",
                        'exercicios' => [
                            m('Como começar uma opinião?', ['I think…', 'I yesterday…', 'I table…', 'I left…'], 'I think…'),
                            t('Traduza: I agree', 'eu concordo|concordo'),
                            c('Complete: I stayed home _____ it rained.', 'because'),
                            emp('Una.', [['I agree', 'eu concordo'], ['I disagree', 'eu discordo'], ['because', 'porque'], ['in my opinion', 'na minha opinião']]),
                            vf('"I don\'t think so" discorda com educação.', true),
                            ordena('Monte:', 'I think this film is great'),
                            m("That's why introduz:", ['uma causa já dita', 'um cumprimento', 'um número', 'uma cor'], 'uma causa já dita'),
                            m('I disagree. significa:', ['eu concordo', 'eu discordo', 'eu não sei', 'eu espero'], 'eu discordo'),
                        ],
                    ],
                    [
                        'titulo' => 'Comparativos',
                        'resumo' => 'bigger, more interesting, as… as',
                        'teoria' => "This city is bigger than mine.\nThis book is more interesting.\nas cheap as · the best / the worst\nIt's not as cold as yesterday.",
                        'exercicios' => [
                            m('Comparativo correto:', ['bigger than', 'more bigger', 'biggest than', 'big that'], 'bigger than'),
                            t('Traduza: more interesting', 'mais interessante'),
                            c('Complete: It is not as cold _____ yesterday.', 'as'),
                            emp('Una.', [['bigger', 'maior'], ['cheaper', 'mais barato'], ['the best', 'o melhor'], ['the worst', 'o pior']]),
                            vf('"As… as" compara igualdade.', true),
                            ordena('Monte:', 'This city is bigger than mine'),
                            m('The best é:', ['comparativo', 'superlativo', 'passado', 'futuro'], 'superlativo'),
                            m('More interesting usa-se com:', ['adjetivos longos', 'só cores', 'só números', 'só nomes'], 'adjetivos longos'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Trabalho e estudos',
                'descricao' => 'Rotina profissional, habilidades e compromissos.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'No trabalho',
                        'resumo' => 'meeting, deadline, I work as, remote',
                        'teoria' => "I work as a designer / teacher / nurse.\nI have a meeting at ten.\nThe deadline is Friday.\nI work remotely two days a week.",
                        'exercicios' => [
                            m('"I work as a teacher" diz:', ['a profissão', 'o preço', 'a idade', 'a cor'], 'a profissão'),
                            t('Traduza: I have a meeting', 'eu tenho uma reuniao|tenho uma reunião|eu tenho uma reunião'),
                            c('Complete: The _____ is Friday. (prazo)', 'deadline'),
                            emp('Una.', [['meeting', 'reunião'], ['deadline', 'prazo'], ['remotely', 'remoto'], ['nurse', 'enfermeiro(a)']]),
                            vf('"I work remotely" significa trabalho à distância.', true),
                            ordena('Monte:', 'I have a meeting at ten'),
                            m('Designer é:', ['uma profissão', 'um país', 'uma refeição', 'um meio de transporte'], 'uma profissão'),
                            m('Two days a week fala de:', ['frequência', 'preço', 'tamanho', 'cor'], 'frequência'),
                        ],
                    ],
                    [
                        'titulo' => 'Habilidades',
                        'resumo' => 'can, good at, I need to, should',
                        'teoria' => "I'm good at writing.\nI can use spreadsheets.\nI need to finish this today.\nYou should send the email now.",
                        'exercicios' => [
                            m('"I\'m good at writing" fala de:', ['habilidade', 'fome', 'direção', 'preço'], 'habilidade'),
                            t('Traduza: You should send the email', 'voce deveria enviar o email|você deveria enviar o e-mail|deveria enviar o email'),
                            c('Complete: I need _____ finish this.', 'to'),
                            emp('Una.', [['good at', 'bom em'], ['need to', 'preciso'], ['should', 'deveria'], ['can', 'consigo / posso']]),
                            vf('"Should" dá conselho, não ordem dura.', true),
                            ordena('Monte:', 'You should send the email now'),
                            m('I can use spreadsheets. descreve:', ['uma ferramenta de trabalho', 'um prato', 'um animal', 'um esporte só'], 'uma ferramenta de trabalho'),
                            m('Need to expressa:', ['obrigação / necessidade', 'cor', 'lugar', 'hora só'], 'obrigação / necessidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Se e quando',
                'descricao' => 'Condições reais: if e when no futuro.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'If it rains',
                        'resumo' => 'if + presente, will',
                        'teoria' => "If it rains, I will stay home.\nIf I finish early, I'll call you.\nUnless I am sick, I will go.\nDon't use will no if.",
                        'exercicios' => [
                            m('Forma correta:', ['If it rains, I will stay', 'If it will rain, I stay', 'If rains, I staying', 'If it rain, I will'], 'If it rains, I will stay'),
                            t('Traduza: If I finish early, I will call you', 'se eu terminar cedo vou te ligar|se eu terminar cedo eu te ligo|se terminar cedo te ligo'),
                            c('Complete: If it rains, I _____ stay home.', 'will'),
                            emp('Una.', [['if', 'se'], ['unless', 'a menos que'], ['early', 'cedo'], ['sick', 'doente']]),
                            vf('No if de condição real usamos presente, não will.', true),
                            ordena('Monte:', 'If I finish early I will call you'),
                            m('Unless I am sick. introduz:', ['uma exceção', 'um cumprimento', 'um preço', 'uma cor'], 'uma exceção'),
                            m('I will stay home. é:', ['o resultado da condição', 'o passado', 'um substantivo', 'uma cor'], 'o resultado da condição'),
                        ],
                    ],
                    [
                        'titulo' => 'When I arrive',
                        'resumo' => 'when, as soon as, before, after',
                        'teoria' => "When I arrive, I'll text you.\nAs soon as I know, I'll tell you.\nBefore we leave, let's eat.\nAfter the class, we can talk.",
                        'exercicios' => [
                            m('When I arrive, I\'ll text you. fala de:', ['uma sequência futura', 'só o passado', 'uma cor', 'um preço'], 'uma sequência futura'),
                            t('Traduza: As soon as I know', 'assim que eu souber|tão logo eu saiba|assim que eu saber'),
                            c('Complete: _____ we leave, let\'s eat.', 'Before'),
                            emp('Una.', [['when', 'quando'], ['as soon as', 'assim que'], ['before', 'antes'], ['after', 'depois']]),
                            vf('"As soon as" indica o momento imediato seguinte.', true),
                            ordena('Monte:', 'When I arrive I will text you'),
                            m('After the class aponta para:', ['depois da aula', 'antes da aula', 'durante o almoço só', 'nunca'], 'depois da aula'),
                            m('Let\'s eat. é:', ['sugestão', 'passado', 'preço', 'nacionalidade'], 'sugestão'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Experiências',
                'descricao' => 'Present perfect simples para falar o que já viveu.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Have you ever…?',
                        'resumo' => 'have been, ever, never, yet',
                        'teoria' => "Have you ever been to Salvador?\nI have never tried this food.\nI haven't finished yet.\nShe's already packed.",
                        'exercicios' => [
                            m('Pergunta de experiência:', ['Have you ever been to Salvador?', 'Did you ever Salvador?', 'Are you Salvador?', 'Have you Salvador?'], 'Have you ever been to Salvador?'),
                            t('Traduza: I have never tried this', 'eu nunca experimentei isso|nunca provei isso|eu nunca provei isto'),
                            c("Complete: I haven't finished _____.", 'yet'),
                            emp('Una.', [['ever', 'alguma vez'], ['never', 'nunca'], ['already', 'já'], ['yet', 'ainda']]),
                            vf('"Yet" em negativa significa ainda não.', true),
                            ordena('Monte:', 'Have you ever been to Salvador'),
                            m("She's already packed. significa:", ['ela já fez as malas', 'ela vai viajar ontem', 'ela não tem mala', 'ela perdeu o voo'], 'ela já fez as malas'),
                            m('Present perfect fala de:', ['experiência até agora', 'só uma cor', 'só um preço', 'só um nome'], 'experiência até agora'),
                        ],
                    ],
                    [
                        'titulo' => 'Contar a história',
                        'resumo' => 'it was, I felt, in the end',
                        'teoria' => "It was my first time.\nI felt nervous, but then I relaxed.\nIn the end, everything went well.\nI would do it again.",
                        'exercicios' => [
                            m('It was my first time. descreve:', ['uma experiência nova', 'um preço', 'uma cor', 'um endereço'], 'uma experiência nova'),
                            t('Traduza: In the end, everything went well', 'no final deu tudo certo|no fim tudo correu bem|no final tudo deu certo'),
                            c('Complete: I felt _____, but then I relaxed.', 'nervous'),
                            emp('Una.', [['first time', 'primeira vez'], ['I felt', 'eu senti'], ['in the end', 'no fim'], ['again', 'de novo']]),
                            vf('"I would do it again" mostra avaliação positiva.', true),
                            ordena('Monte:', 'I would do it again'),
                            m('I felt nervous. fala de:', ['emoção', 'tamanho de roupa', 'moeda', 'direção'], 'emoção'),
                            m('But then I relaxed. mostra:', ['mudança no meio da história', 'um pedido de preço', 'uma saudação', 'um número'], 'mudança no meio da história'),
                        ],
                    ],
                ],
            ],
        ],
    ];
}

function niveis_espanhol(): array
{
    return [
        'descricao' => 'Ruta MCER: de A1 a C2, del saludo a la precisión profesional.',
        'palavras' => [
            ['Ayer', 'Ontem', 'Ayer trabajé.', 'A2'],
            ['Ya', 'Já', 'Ya he comido.', 'A2'],
            ['Porque', 'Porque', 'Me quedé en casa porque llovió.', 'B1'],
            ['Aunque', 'Embora', 'Aunque estaba cansado, fui.', 'B1'],
            ['Si', 'Se', 'Si llueve, me quedo en casa.', 'B2'],
            ['Experiencia', 'Experiência', 'Fue una gran experiencia.', 'B2'],
        ],
        'unidades' => [
            [
                'titulo' => 'Ayer',
                'descricao' => 'Pretérito para contar o que aconteceu.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Pretérito',
                        'resumo' => 'trabajé, fui, tuve, fue',
                        'teoria' => "Ayer trabajé. Ella fue al mercado.\nfui / fue · tuve · ¿Qué hiciste?\nNo fui. ¿Fuiste tú?",
                        'exercicios' => [
                            m('Qual está no passado?', ['Ayer voy', 'Ayer fui', 'Ayer yendo', 'Ayer va'], 'Ayer fui'),
                            t('Traduza: Ayer trabajé', 'ontem eu trabalhei|trabalhei ontem'),
                            c('Complete: Ella no _____. (ir)', 'fue'),
                            emp('Una.', [['fui', 'eu fui'], ['tuve', 'tive'], ['hice', 'fiz'], ['fue', 'foi']]),
                            vf('"¿Qué hiciste?" pergunta o que você fez.', true),
                            ordena('Monte:', 'Que hiciste ayer'),
                            m('Ellos fueron. usa:', ['fui', 'fue', 'fueron', 'iba'], 'fueron'),
                            m('Pergunta correta:', ['¿Fuiste al mercado?', '¿Ibas fuiste?', '¿Fue tú mercado?', '¿Ir ayer?'], '¿Fuiste al mercado?'),
                        ],
                    ],
                    [
                        'titulo' => 'Contar el día',
                        'resumo' => 'primero, luego, después, al final',
                        'teoria' => "primero · luego · después · al final\nPor la mañana… · Por la tarde… · Por la noche…\nFue un día largo.",
                        'exercicios' => [
                            m('Qual organiza a história?', ['primero / luego', 'hola / adiós', 'izquierda / derecha', 'sí / no'], 'primero / luego'),
                            t('Traduza: Fue un día largo', 'foi um dia longo|foi um longo dia'),
                            c('Complete: _____ fui a casa. (depois)', 'Después'),
                            emp('Una.', [['mañana', 'manhã'], ['tarde', 'tarde'], ['noche', 'noite'], ['al final', 'por fim']]),
                            vf('"Al final" fecha a sequência.', true),
                            ordena('Monte:', 'Primero desayune'),
                            m('Por la noche dormí. descreve:', ['o fim do dia', 'o futuro', 'um pedido', 'uma cor'], 'o fim do dia'),
                            m('Después significa:', ['antes', 'depois', 'em vez de', 'apesar de'], 'depois'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Planes',
                'descricao' => 'Ir a + infinitivo e convites.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Voy a…',
                        'resumo' => 'planos com ir a',
                        'teoria' => "Voy a viajar en julio.\nElla va a estudiar esta noche.\n¿Vas a venir?\nUso: plano já decidido.",
                        'exercicios' => [
                            m('Plano já decidido:', ['Voy a viajar', 'Yo viajando', 'Voy viajar a', 'Iré yendo'], 'Voy a viajar'),
                            t('Traduza: Voy a estudiar', 'vou estudar|eu vou estudar'),
                            c('Complete: Ella va _____ cocinar.', 'a'),
                            emp('Una.', [['esta noche', 'hoje à noite'], ['mañana', 'amanhã'], ['la semana que viene', 'semana que vem'], ['en julio', 'em julho']]),
                            vf('"¿Vas a venir?" pergunta sobre um plano.', true),
                            ordena('Monte:', 'Vamos a viajar'),
                            m('La semana que viene aponta para:', ['passado', 'futuro próximo', 'agora', 'nunca'], 'futuro próximo'),
                            m('Negativa:', ['No voy a ir', 'Yo no yendo', 'No voy ir', 'Yo no a ir'], 'No voy a ir'),
                        ],
                    ],
                    [
                        'titulo' => 'Invitaciones',
                        'resumo' => '¿Te gustaría? claro, no puedo',
                        'teoria' => "¿Te gustaría salir?\nClaro que sí. / Me encantaría.\nLo siento, no puedo.\nQuizá más tarde.",
                        'exercicios' => [
                            m('Convite educado:', ['¿Te gustaría salir?', '¿Sales precio?', '¿Dónde color?', '¿Cuántos?'], '¿Te gustaría salir?'),
                            t('Traduza: Lo siento, no puedo', 'desculpa nao posso|desculpe, não posso|sinto muito não posso'),
                            c('Complete: Me _____aría. (encantar)', 'encant'),
                            emp('Una.', [['claro', 'claro'], ['quizá', 'talvez'], ['no puedo', 'não posso'], ['me encantaría', 'adoraria']]),
                            vf('"¿Te gustaría?" é um convite.', true),
                            ordena('Monte:', 'Te gustaria salir'),
                            m('Me encantaría. responde:', ['um convite', 'um preço', 'um nome', 'uma hora'], 'um convite'),
                            m('Quizá indica:', ['certeza', 'possibilidade', 'passado', 'ordem'], 'possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Opiniones',
                'descricao' => 'Comparar, concordar e explicar.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Creo que…',
                        'resumo' => 'creo, porque, estoy de acuerdo',
                        'teoria' => "Creo que esta película es genial.\nNo creo.\nEstoy de acuerdo / No estoy de acuerdo.\nporque · por eso · en mi opinión",
                        'exercicios' => [
                            m('Começar opinião:', ['Creo que…', 'Ayer mesa…', 'Hola precio…', 'Izquierda…'], 'Creo que…'),
                            t('Traduza: Estoy de acuerdo', 'eu concordo|estou de acordo|concordo'),
                            c('Complete: Me quedé _____ llovió.', 'porque'),
                            emp('Una.', [['estoy de acuerdo', 'concordo'], ['no estoy de acuerdo', 'discordo'], ['porque', 'porque'], ['en mi opinión', 'na minha opinião']]),
                            vf('"No creo" discorda com educação.', true),
                            ordena('Monte:', 'Creo que esta pelicula es genial'),
                            m('Por eso introduz:', ['a consequência', 'um cumprimento', 'um número', 'uma cor'], 'a consequência'),
                            m('No estoy de acuerdo. significa:', ['concordo', 'discordo', 'não sei', 'espero'], 'discordo'),
                        ],
                    ],
                    [
                        'titulo' => 'Comparativos',
                        'resumo' => 'más… que, tan… como, el mejor',
                        'teoria' => "Esta ciudad es más grande que la mía.\nEste libro es más interesante.\ntan barato como · el mejor / el peor",
                        'exercicios' => [
                            m('Comparativo correto:', ['más grande que', 'más grande de que', 'grande más que', 'el más que'], 'más grande que'),
                            t('Traduza: más interesante', 'mais interessante'),
                            c('Complete: No hace tanto frío _____ ayer.', 'como'),
                            emp('Una.', [['más grande', 'maior'], ['más barato', 'mais barato'], ['el mejor', 'o melhor'], ['el peor', 'o pior']]),
                            vf('"Tan… como" compara igualdade.', true),
                            ordena('Monte:', 'Esta ciudad es mas grande que la mia'),
                            m('El mejor é:', ['comparativo', 'superlativo', 'passado', 'futuro'], 'superlativo'),
                            m('Más interesante usa-se para:', ['qualificar e comparar', 'só cores', 'só horas', 'só nomes próprios'], 'qualificar e comparar'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Trabajo y estudios',
                'descricao' => 'Profissão, prazos e conselhos.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'En el trabajo',
                        'resumo' => 'reunión, plazo, trabajo como, remoto',
                        'teoria' => "Trabajo como diseñador / profesor / enfermero.\nTengo una reunión a las diez.\nEl plazo es el viernes.\nTrabajo en remoto dos días a la semana.",
                        'exercicios' => [
                            m('"Trabajo como profesor" diz:', ['a profissão', 'o preço', 'a idade', 'a cor'], 'a profissão'),
                            t('Traduza: Tengo una reunión', 'tenho uma reuniao|tenho uma reunião|eu tenho uma reunião'),
                            c('Complete: El _____ es el viernes. (prazo)', 'plazo'),
                            emp('Una.', [['reunión', 'reunião'], ['plazo', 'prazo'], ['en remoto', 'remoto'], ['enfermero', 'enfermeiro']]),
                            vf('"Trabajo en remoto" é trabalho à distância.', true),
                            ordena('Monte:', 'Tengo una reunion a las diez'),
                            m('Diseñador é:', ['uma profissão', 'um país', 'uma refeição', 'um transporte'], 'uma profissão'),
                            m('Dos días a la semana fala de:', ['frequência', 'preço', 'tamanho', 'cor'], 'frequência'),
                        ],
                    ],
                    [
                        'titulo' => 'Habilidades',
                        'resumo' => 'se me da bien, necesito, deberías',
                        'teoria' => "Se me da bien escribir.\nSé usar hojas de cálculo.\nNecesito terminar esto hoy.\nDeberías enviar el correo ahora.",
                        'exercicios' => [
                            m('"Se me da bien escribir" fala de:', ['habilidade', 'fome', 'direção', 'preço'], 'habilidade'),
                            t('Traduza: Deberías enviar el correo', 'voce deveria enviar o email|você deveria enviar o e-mail'),
                            c('Complete: Necesito _____ esto hoy.', 'terminar'),
                            emp('Una.', [['se me da bien', 'sou bom em'], ['necesito', 'preciso'], ['deberías', 'você deveria'], ['sé', 'eu sei']]),
                            vf('"Deberías" dá conselho.', true),
                            ordena('Monte:', 'Deberias enviar el correo ahora'),
                            m('Hojas de cálculo são:', ['planilhas', 'pratos', 'sapatos', 'ruas'], 'planilhas'),
                            m('Necesito expressa:', ['necessidade', 'cor', 'lugar', 'só hora'], 'necessidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Si y cuando',
                'descricao' => 'Condições reais com si e cuando.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Si llueve',
                        'resumo' => 'si + presente, futuro',
                        'teoria' => "Si llueve, me quedaré en casa.\nSi termino pronto, te llamo.\nA menos que esté enfermo, iré.",
                        'exercicios' => [
                            m('Forma correta:', ['Si llueve, me quedaré', 'Si lloveré, me quedo', 'Si lluvia, quedo', 'Si llueve, quedaré me'], 'Si llueve, me quedaré'),
                            t('Traduza: Si termino pronto, te llamo', 'se eu terminar cedo te ligo|se terminar cedo eu te ligo'),
                            c('Complete: Si llueve, me _____ en casa.', 'quedare|quedaré'),
                            emp('Una.', [['si', 'se'], ['a menos que', 'a menos que'], ['pronto', 'cedo'], ['enfermo', 'doente']]),
                            vf('Na condição real, si vai com presente.', true),
                            ordena('Monte:', 'Si termino pronto te llamo'),
                            m('A menos que esté enfermo. é:', ['uma exceção', 'um oi', 'um preço', 'uma cor'], 'uma exceção'),
                            m('Me quedaré en casa. é:', ['o resultado', 'o passado', 'um substantivo', 'uma cor'], 'o resultado'),
                        ],
                    ],
                    [
                        'titulo' => 'Cuando llegue',
                        'resumo' => 'cuando, en cuanto, antes, después',
                        'teoria' => "Cuando llegue, te escribo.\nEn cuanto sepa, te aviso.\nAntes de salir, comemos.\nDespués de la clase, hablamos.",
                        'exercicios' => [
                            m('Cuando llegue, te escribo. fala de:', ['futuro em sequência', 'só passado', 'uma cor', 'um preço'], 'futuro em sequência'),
                            t('Traduza: En cuanto sepa', 'assim que eu souber|tão logo eu saiba'),
                            c('Complete: _____ de salir, comemos.', 'Antes'),
                            emp('Una.', [['cuando', 'quando'], ['en cuanto', 'assim que'], ['antes', 'antes'], ['después', 'depois']]),
                            vf('"En cuanto" indica o momento imediato.', true),
                            ordena('Monte:', 'Cuando llegue te escribo'),
                            m('Después de la clase é:', ['depois da aula', 'antes da aula', 'no almoço só', 'nunca'], 'depois da aula'),
                            m('Hablamos. aqui é:', ['combinado / presente com valor de futuro', 'uma cor', 'um país', 'um número'], 'combinado / presente com valor de futuro'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Experiencias',
                'descricao' => 'Pretérito perfecto para o que já viveu.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => '¿Has estado…?',
                        'resumo' => 'he estado, alguna vez, nunca, todavía',
                        'teoria' => "¿Has estado en Salvador?\nNunca he probado esta comida.\nTodavía no he terminado.\nYa ha hecho la maleta.",
                        'exercicios' => [
                            m('Pergunta de experiência:', ['¿Has estado en Salvador?', '¿Eres Salvador?', '¿Estuviste ser?', '¿Has Salvador?'], '¿Has estado en Salvador?'),
                            t('Traduza: Nunca he probado esto', 'nunca provei isso|eu nunca experimentei isso'),
                            c('Complete: Todavía no he _____.', 'terminado'),
                            emp('Una.', [['alguna vez', 'alguma vez'], ['nunca', 'nunca'], ['ya', 'já'], ['todavía', 'ainda']]),
                            vf('"Todavía no" significa ainda não.', true),
                            ordena('Monte:', 'Has estado en Salvador'),
                            m('Ya ha hecho la maleta. significa:', ['já fez as malas', 'vai viajar ontem', 'não tem mala', 'perdeu o voo'], 'já fez as malas'),
                            m('Pretérito perfecto fala de:', ['experiência até agora', 'só uma cor', 'só um preço', 'só um nome'], 'experiência até agora'),
                        ],
                    ],
                    [
                        'titulo' => 'Contar la historia',
                        'resumo' => 'fue, me sentí, al final',
                        'teoria' => "Fue la primera vez.\nAl principio estaba nervioso, luego me relajé.\nAl final, todo salió bien.\nLo haría otra vez.",
                        'exercicios' => [
                            m('Fue la primera vez. descreve:', ['experiência nova', 'preço', 'cor', 'endereço'], 'experiência nova'),
                            t('Traduza: Al final, todo salió bien', 'no final deu tudo certo|no fim tudo correu bem'),
                            c('Complete: Al principio estaba _____.', 'nervioso'),
                            emp('Una.', [['primera vez', 'primeira vez'], ['me sentí', 'eu senti'], ['al final', 'no fim'], ['otra vez', 'de novo']]),
                            vf('"Lo haría otra vez" avalia de forma positiva.', true),
                            ordena('Monte:', 'Lo haria otra vez'),
                            m('Estaba nervioso. fala de:', ['emoção', 'tamanho', 'moeda', 'direção'], 'emoção'),
                            m('Luego me relajé. mostra:', ['mudança na história', 'um preço', 'um oi', 'um número'], 'mudança na história'),
                        ],
                    ],
                ],
            ],
        ],
    ];
}

function niveis_frances(): array
{
    return [
        'descricao' => 'Parcours A1 à A4 : du salut aux expériences, opinions et projets.',
        'palavras' => [
            ['Hier', 'Ontem', "J'ai travaillé hier.", 'A2'],
            ['Déjà', 'Já', "J'ai déjà mangé.", 'A2'],
            ['Parce que', 'Porque', 'Je suis resté parce qu\'il a plu.', 'B1'],
            ['Bien que', 'Embora', "Bien que je sois fatigué, j'y suis allé.", 'B1'],
            ['Si', 'Se', 'S\'il pleut, je reste.', 'B2'],
            ['Expérience', 'Experiência', "C'était une belle expérience.", 'B2'],
        ],
        'unidades' => [
            [
                'titulo' => 'Hier',
                'descricao' => 'Passé composé para contar o que aconteceu.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Passé composé',
                        'resumo' => "j'ai travaillé, je suis allé",
                        'teoria' => "J'ai travaillé hier. Elle est allée au marché.\navoir + participe · être com alguns verbos\nTu as fait quoi ?",
                        'exercicios' => [
                            m('Qual está no passado?', ["Je vais hier", "Je suis allé hier", "Je aller hier", "Je va hier"], "Je suis allé hier"),
                            t('Traduza: J\'ai travaillé hier', 'eu trabalhei ontem|trabalhei ontem'),
                            c('Complete: Elle n\'est pas _____. (allée)', 'allee|allée'),
                            emp('Una.', [['j\'ai fait', 'eu fiz'], ['je suis allé', 'eu fui'], ['j\'ai eu', 'eu tive'], ['c\'était', 'foi / era']]),
                            vf('"Tu as fait quoi ?" pergunta o que você fez.', true),
                            ordena('Monte:', "J'ai travaille hier"),
                            m('Ils sont allés. usa:', ['être no plural', 'só avoir', 'futuro', 'imperativo'], 'être no plural'),
                            m('Pergunta correta:', ['Tu es allé au marché ?', 'Tu aller marché ?', 'Es tu marché ?', 'Allé tu ?'], 'Tu es allé au marché ?'),
                        ],
                    ],
                    [
                        'titulo' => 'Raconter la journée',
                        'resumo' => "d'abord, ensuite, puis, enfin",
                        'teoria' => "d'abord · ensuite · puis · enfin\nLe matin… · L'après-midi… · Le soir…\nC'était une longue journée.",
                        'exercicios' => [
                            m('Qual organiza a história?', ["d'abord / ensuite", 'bonjour / au revoir', 'gauche / droite', 'oui / non'], "d'abord / ensuite"),
                            t('Traduza: C\'était une longue journée', 'foi um dia longo|foi um longo dia'),
                            c('Complete: _____ je suis rentré. (depois)', 'Ensuite|Puis'),
                            emp('Una.', [['matin', 'manhã'], ['après-midi', 'tarde'], ['soir', 'noite'], ['enfin', 'por fim']]),
                            vf('"Enfin" fecha a sequência.', true),
                            ordena('Monte:', "D'abord j'ai pris le petit-dejeuner"),
                            m('Le soir, j\'ai dormi. descreve:', ['o fim do dia', 'o futuro', 'um pedido', 'uma cor'], 'o fim do dia'),
                            m('Ensuite significa:', ['antes', 'depois', 'em vez de', 'apesar de'], 'depois'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Projets',
                'descricao' => 'Aller + infinitif e convites.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Je vais…',
                        'resumo' => 'planos com aller',
                        'teoria' => "Je vais voyager en juillet.\nElle va étudier ce soir.\nTu vas venir ?\nUsage : plan déjà décidé.",
                        'exercicios' => [
                            m('Plano já decidido:', ['Je vais voyager', 'Je voyageant', 'Je vais voyage', 'J\'irai allant'], 'Je vais voyager'),
                            t('Traduza: Je vais étudier', 'vou estudar|eu vou estudar'),
                            c('Complete: Elle va _____ cuisiner.', 'a'),
                            emp('Una.', [['ce soir', 'hoje à noite'], ['demain', 'amanhã'], ['la semaine prochaine', 'semana que vem'], ['en juillet', 'em julho']]),
                            vf('"Tu vas venir ?" pergunta sobre um plano.', true),
                            ordena('Monte:', 'Nous allons voyager'),
                            m('La semaine prochaine aponta para:', ['passado', 'futuro próximo', 'agora', 'nunca'], 'futuro próximo'),
                            m('Negativa:', ['Je ne vais pas y aller', 'Je pas vais', 'Je no vais', 'Je vais ne'], 'Je ne vais pas y aller'),
                        ],
                    ],
                    [
                        'titulo' => 'Invitations',
                        'resumo' => 'tu veux, avec plaisir, je ne peux pas',
                        'teoria' => "Tu veux sortir ?\nAvec plaisir. / J'aimerais bien.\nDésolé, je ne peux pas.\nPeut-être plus tard.",
                        'exercicios' => [
                            m('Convite:', ['Tu veux sortir ?', 'Tu prix ?', 'Tu couleur ?', 'Tu combien ?'], 'Tu veux sortir ?'),
                            t('Traduza: Désolé, je ne peux pas', 'desculpa nao posso|desculpe, não posso'),
                            c('Complete: Avec _____.', 'plaisir'),
                            emp('Una.', [['avec plaisir', 'com prazer'], ['peut-être', 'talvez'], ['je ne peux pas', 'não posso'], ["j'aimerais", 'eu gostaria']]),
                            vf('"Tu veux sortir ?" é um convite.', true),
                            ordena('Monte:', 'Tu veux sortir'),
                            m("J'aimerais bien. responde:", ['um convite', 'um preço', 'um nome', 'uma hora'], 'um convite'),
                            m('Peut-être indica:', ['certeza', 'possibilidade', 'passado', 'ordem'], 'possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Avis',
                'descricao' => 'Comparar, concordar e explicar.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Je pense que…',
                        'resumo' => 'je pense, parce que, je suis d\'accord',
                        'teoria' => "Je pense que ce film est génial.\nJe ne pense pas.\nJe suis d'accord / je ne suis pas d'accord.\nparce que · c'est pour ça · à mon avis",
                        'exercicios' => [
                            m('Começar opinião:', ['Je pense que…', 'Hier table…', 'Bonjour prix…', 'Gauche…'], 'Je pense que…'),
                            t('Traduza: Je suis d\'accord', 'eu concordo|estou de acordo'),
                            c('Complete: Je suis resté _____ il a plu.', 'parce que'),
                            emp('Una.', [['je suis d\'accord', 'concordo'], ['je ne suis pas d\'accord', 'discordo'], ['parce que', 'porque'], ['à mon avis', 'na minha opinião']]),
                            vf('"Je ne pense pas" discorda com educação.', true),
                            ordena('Monte:', 'Je pense que ce film est genial'),
                            m("C'est pour ça introduz:", ['a consequência', 'um oi', 'um número', 'uma cor'], 'a consequência'),
                            m('Je ne suis pas d\'accord. significa:', ['concordo', 'discordo', 'não sei', 'espero'], 'discordo'),
                        ],
                    ],
                    [
                        'titulo' => 'Comparatifs',
                        'resumo' => 'plus… que, aussi… que, le meilleur',
                        'teoria' => "Cette ville est plus grande que la mienne.\nCe livre est plus intéressant.\naussi bon marché que · le meilleur / le pire",
                        'exercicios' => [
                            m('Comparativo correto:', ['plus grande que', 'plus grande de', 'grande plus que', 'le plus que'], 'plus grande que'),
                            t('Traduza: plus intéressant', 'mais interessante'),
                            c('Complete: Il ne fait pas aussi froid _____ hier.', 'que'),
                            emp('Una.', [['plus grande', 'maior'], ['moins cher', 'mais barato'], ['le meilleur', 'o melhor'], ['le pire', 'o pior']]),
                            vf('"Aussi… que" compara igualdade.', true),
                            ordena('Monte:', 'Cette ville est plus grande que la mienne'),
                            m('Le meilleur é:', ['comparativo', 'superlativo', 'passado', 'futuro'], 'superlativo'),
                            m('Plus intéressant serve para:', ['comparar qualidade', 'só cores', 'só horas', 'só nomes'], 'comparar qualidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Travail et études',
                'descricao' => 'Profissão, prazos e conselhos.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Au travail',
                        'resumo' => 'réunion, délai, je travaille comme, distanciel',
                        'teoria' => "Je travaille comme designer / prof / infirmier.\nJ'ai une réunion à dix heures.\nLe délai est vendredi.\nJe travaille à distance deux jours par semaine.",
                        'exercicios' => [
                            m('"Je travaille comme prof" diz:', ['a profissão', 'o preço', 'a idade', 'a cor'], 'a profissão'),
                            t('Traduza: J\'ai une réunion', 'tenho uma reuniao|tenho uma reunião'),
                            c('Complete: Le _____ est vendredi. (prazo)', 'delai|délai'),
                            emp('Una.', [['réunion', 'reunião'], ['délai', 'prazo'], ['à distance', 'remoto'], ['infirmier', 'enfermeiro']]),
                            vf('"À distance" é trabalho remoto.', true),
                            ordena('Monte:', "J'ai une reunion a dix heures"),
                            m('Designer é:', ['uma profissão', 'um país', 'uma refeição', 'um transporte'], 'uma profissão'),
                            m('Deux jours par semaine fala de:', ['frequência', 'preço', 'tamanho', 'cor'], 'frequência'),
                        ],
                    ],
                    [
                        'titulo' => 'Compétences',
                        'resumo' => 'je suis doué, je dois, tu devrais',
                        'teoria' => "Je suis doué pour l'écriture.\nJe sais utiliser un tableur.\nJe dois finir ça aujourd'hui.\nTu devrais envoyer l'e-mail maintenant.",
                        'exercicios' => [
                            m('"Je suis doué pour…" fala de:', ['habilidade', 'fome', 'direção', 'preço'], 'habilidade'),
                            t('Traduza: Tu devrais envoyer l\'e-mail', 'voce deveria enviar o email|você deveria enviar o e-mail'),
                            c('Complete: Je dois _____ ça aujourd\'hui.', 'finir'),
                            emp('Una.', [['doué', 'hábil / talentoso'], ['je dois', 'eu preciso / devo'], ['tu devrais', 'você deveria'], ['je sais', 'eu sei']]),
                            vf('"Tu devrais" dá conselho.', true),
                            ordena('Monte:', 'Tu devrais envoyer l e-mail maintenant'),
                            m('Un tableur é:', ['planilha', 'prato', 'sapato', 'rua'], 'planilha'),
                            m('Je dois expressa:', ['necessidade / dever', 'cor', 'lugar', 'só hora'], 'necessidade / dever'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Si et quand',
                'descricao' => 'Condições reais com si e quand.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'S\'il pleut',
                        'resumo' => 'si + présent, futur',
                        'teoria' => "S'il pleut, je resterai à la maison.\nSi je finis tôt, je t'appelle.\nSauf si je suis malade, j'irai.",
                        'exercicios' => [
                            m('Forma correta:', ["S'il pleut, je resterai", "S'il pleuvra, je reste", 'Si pluie, je reste', "S'il pleut, resterai je"], "S'il pleut, je resterai"),
                            t('Traduza: Si je finis tôt, je t\'appelle', 'se eu terminar cedo te ligo|se terminar cedo eu te ligo'),
                            c('Complete: S\'il pleut, je _____ à la maison.', 'resterai'),
                            emp('Una.', [['si', 'se'], ['sauf si', 'a menos que'], ['tôt', 'cedo'], ['malade', 'doente']]),
                            vf('Na condição real, si vai com présent.', true),
                            ordena('Monte:', 'Si je finis tot je t appelle'),
                            m('Sauf si je suis malade. é:', ['uma exceção', 'um oi', 'um preço', 'uma cor'], 'uma exceção'),
                            m('Je resterai à la maison. é:', ['o resultado', 'o passado', 'um substantivo', 'uma cor'], 'o resultado'),
                        ],
                    ],
                    [
                        'titulo' => 'Quand j\'arrive',
                        'resumo' => 'quand, dès que, avant, après',
                        'teoria' => "Quand j'arrive, je t'envoie un message.\nDès que je sais, je te dis.\nAvant de partir, on mange.\nAprès le cours, on peut parler.",
                        'exercicios' => [
                            m('Quand j\'arrive, je t\'envoie un message. fala de:', ['futuro em sequência', 'só passado', 'uma cor', 'um preço'], 'futuro em sequência'),
                            t('Traduza: Dès que je sais', 'assim que eu souber|tão logo eu saiba'),
                            c('Complete: _____ de partir, on mange.', 'Avant'),
                            emp('Una.', [['quand', 'quando'], ['dès que', 'assim que'], ['avant', 'antes'], ['après', 'depois']]),
                            vf('"Dès que" indica o momento imediato.', true),
                            ordena('Monte:', "Quand j'arrive je t envoie un message"),
                            m('Après le cours é:', ['depois da aula', 'antes da aula', 'no almoço só', 'nunca'], 'depois da aula'),
                            m('On peut parler. é:', ['sugestão / possibilidade', 'uma cor', 'um país', 'um número'], 'sugestão / possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Expériences',
                'descricao' => 'Passé composé com déjà / jamais para o que já viveu.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Tu es déjà allé… ?',
                        'resumo' => 'déjà, jamais, pas encore',
                        'teoria' => "Tu es déjà allé à Salvador ?\nJe n'ai jamais goûté ça.\nJe n'ai pas encore fini.\nElle a déjà fait sa valise.",
                        'exercicios' => [
                            m('Pergunta de experiência:', ['Tu es déjà allé à Salvador ?', 'Tu es Salvador ?', 'As-tu Salvador ?', 'Tu Salvador ?'], 'Tu es déjà allé à Salvador ?'),
                            t('Traduza: Je n\'ai jamais goûté ça', 'eu nunca provei isso|nunca experimentei isso'),
                            c('Complete: Je n\'ai pas _____ fini.', 'encore'),
                            emp('Una.', [['déjà', 'já'], ['jamais', 'nunca'], ['pas encore', 'ainda não'], ['goûter', 'provar']]),
                            vf('"Pas encore" significa ainda não.', true),
                            ordena('Monte:', 'Tu es deja alle a Salvador'),
                            m('Elle a déjà fait sa valise. significa:', ['já fez as malas', 'vai viajar ontem', 'não tem mala', 'perdeu o voo'], 'já fez as malas'),
                            m('Déjà / jamais falam de:', ['experiência até agora', 'só uma cor', 'só um preço', 'só um nome'], 'experiência até agora'),
                        ],
                    ],
                    [
                        'titulo' => 'Raconter',
                        'resumo' => "c'était, je me sentais, au final",
                        'teoria' => "C'était la première fois.\nAu début j'étais stressé, puis je me suis détendu.\nAu final, tout s'est bien passé.\nJe le referais.",
                        'exercicios' => [
                            m("C'était la première fois. descreve:", ['experiência nova', 'preço', 'cor', 'endereço'], 'experiência nova'),
                            t('Traduza: Au final, tout s\'est bien passé', 'no final deu tudo certo|no fim tudo correu bem'),
                            c('Complete: Au début j\'étais _____.', 'stresse|stressé'),
                            emp('Una.', [['première fois', 'primeira vez'], ['je me sentais', 'eu me sentia'], ['au final', 'no fim'], ['referais', 'faria de novo']]),
                            vf('"Je le referais" avalia de forma positiva.', true),
                            ordena('Monte:', 'Je le referais'),
                            m("J'étais stressé. fala de:", ['emoção', 'tamanho', 'moeda', 'direção'], 'emoção'),
                            m('Puis je me suis détendu. mostra:', ['mudança na história', 'um preço', 'um oi', 'um número'], 'mudança na história'),
                        ],
                    ],
                ],
            ],
        ],
    ];
}

function niveis_italiano(): array
{
    return [
        'descricao' => 'Percorso A1–A4: dal ciao a raccontare esperienze, opinioni e progetti.',
        'palavras' => [
            ['Ieri', 'Ontem', 'Ieri ho lavorato.', 'A2'],
            ['Già', 'Já', 'Ho già mangiato.', 'A2'],
            ['Perché', 'Porque', 'Sono rimasto perché pioveva.', 'B1'],
            ['Anche se', 'Embora', 'Anche se ero stanco, sono andato.', 'B1'],
            ['Se', 'Se', 'Se piove, resto a casa.', 'B2'],
            ['Esperienza', 'Experiência', 'È stata una bella esperienza.', 'B2'],
        ],
        'unidades' => [
            [
                'titulo' => 'Ieri',
                'descricao' => 'Passato prossimo para contar o que aconteceu.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Passato prossimo',
                        'resumo' => 'ho lavorato, sono andato',
                        'teoria' => "Ieri ho lavorato. Lei è andata al mercato.\navere + participio · essere com alguns verbos\nChe hai fatto?",
                        'exercicios' => [
                            m('Qual está no passado?', ['Ieri vado', 'Ieri sono andato', 'Ieri andando', 'Ieri va'], 'Ieri sono andato'),
                            t('Traduza: Ieri ho lavorato', 'ontem eu trabalhei|trabalhei ontem'),
                            c('Complete: Lei non è _____. (andata)', 'andata'),
                            emp('Una.', [['ho fatto', 'eu fiz'], ['sono andato', 'eu fui'], ['ho avuto', 'eu tive'], ['è stato', 'foi']]),
                            vf('"Che hai fatto?" pergunta o que você fez.', true),
                            ordena('Monte:', 'Che hai fatto ieri'),
                            m('Loro sono andati. usa:', ['essere no plural', 'só avere', 'futuro', 'imperativo'], 'essere no plural'),
                            m('Pergunta correta:', ['Sei andato al mercato?', 'Andare tu mercato?', 'Sei mercato?', 'Andato tu?'], 'Sei andato al mercato?'),
                        ],
                    ],
                    [
                        'titulo' => 'Raccontare la giornata',
                        'resumo' => 'prima, poi, dopo, alla fine',
                        'teoria' => "prima · poi · dopo · alla fine\nLa mattina… · Il pomeriggio… · La sera…\nÈ stata una giornata lunga.",
                        'exercicios' => [
                            m('Qual organiza a história?', ['prima / poi', 'ciao / arrivederci', 'sinistra / destra', 'sì / no'], 'prima / poi'),
                            t('Traduza: È stata una giornata lunga', 'foi um dia longo|foi um longo dia'),
                            c('Complete: _____ sono tornato a casa. (depois)', 'Poi|Dopo'),
                            emp('Una.', [['mattina', 'manhã'], ['pomeriggio', 'tarde'], ['sera', 'noite'], ['alla fine', 'por fim']]),
                            vf('"Alla fine" fecha a sequência.', true),
                            ordena('Monte:', 'Prima ho fatto colazione'),
                            m('La sera ho dormito. descreve:', ['o fim do dia', 'o futuro', 'um pedido', 'uma cor'], 'o fim do dia'),
                            m('Dopo significa:', ['antes', 'depois', 'em vez de', 'apesar de'], 'depois'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Piani',
                'descricao' => 'Stare per / andare a e convites.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Ho intenzione di…',
                        'resumo' => 'planos com andare a / intenzione',
                        'teoria' => "Vado a viaggiare a luglio.\nLei sta per studiare stasera.\nVieni?\nUso: piano già deciso.",
                        'exercicios' => [
                            m('Plano já decidido:', ['Vado a viaggiare', 'Io viaggiando', 'Vado viaggiare', 'Andrò andando'], 'Vado a viaggiare'),
                            t('Traduza: Vado a studiare', 'vou estudar|eu vou estudar'),
                            c('Complete: Lei sta _____ studiare.', 'per'),
                            emp('Una.', [['stasera', 'hoje à noite'], ['domani', 'amanhã'], ['la settimana prossima', 'semana que vem'], ['a luglio', 'em julho']]),
                            vf('"Vieni?" pode confirmar um plano informal.', true),
                            ordena('Monte:', 'Andiamo a viaggiare'),
                            m('La settimana prossima aponta para:', ['passado', 'futuro próximo', 'agora', 'nunca'], 'futuro próximo'),
                            m('Negativa:', ['Non vado', 'Io non andando', 'Non vo a', 'Io no andare'], 'Non vado'),
                        ],
                    ],
                    [
                        'titulo' => 'Inviti',
                        'resumo' => 'ti va, volentieri, non posso',
                        'teoria' => "Ti va di uscire?\nVolentieri. / Mi piacerebbe.\nScusa, non posso.\nForse più tardi.",
                        'exercicios' => [
                            m('Convite:', ['Ti va di uscire?', 'Ti prezzo?', 'Ti colore?', 'Ti quanto?'], 'Ti va di uscire?'),
                            t('Traduza: Scusa, non posso', 'desculpa nao posso|desculpe, não posso'),
                            c('Complete: Mi _____bbe. (piacere)', 'piacere'),
                            emp('Una.', [['volentieri', 'com prazer'], ['forse', 'talvez'], ['non posso', 'não posso'], ['mi piacerebbe', 'eu gostaria']]),
                            vf('"Ti va di…?" é um convite.', true),
                            ordena('Monte:', 'Ti va di uscire'),
                            m('Volentieri. responde:', ['um convite', 'um preço', 'um nome', 'uma hora'], 'um convite'),
                            m('Forse indica:', ['certeza', 'possibilidade', 'passado', 'ordem'], 'possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Opinioni',
                'descricao' => 'Comparar, concordar e explicar.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Secondo me…',
                        'resumo' => 'penso, perché, sono d\'accordo',
                        'teoria' => "Penso che questo film sia bello. / Secondo me è bello.\nNon sono d'accordo.\nperché · per questo · secondo me",
                        'exercicios' => [
                            m('Começar opinião:', ['Secondo me…', 'Ieri tavolo…', 'Ciao prezzo…', 'Sinistra…'], 'Secondo me…'),
                            t('Traduza: Sono d\'accordo', 'eu concordo|estou de acordo'),
                            c('Complete: Sono rimasto _____ pioveva.', 'perche|perché'),
                            emp('Una.', [['sono d\'accordo', 'concordo'], ['non sono d\'accordo', 'discordo'], ['perché', 'porque'], ['secondo me', 'na minha opinião']]),
                            vf('"Non sono d\'accordo" discorda.', true),
                            ordena('Monte:', 'Secondo me questo film e bello'),
                            m('Per questo introduz:', ['a consequência', 'um oi', 'um número', 'uma cor'], 'a consequência'),
                            m('Non sono d\'accordo. significa:', ['concordo', 'discordo', 'não sei', 'espero'], 'discordo'),
                        ],
                    ],
                    [
                        'titulo' => 'Comparativi',
                        'resumo' => 'più… di, (così)… come, il migliore',
                        'teoria' => "Questa città è più grande della mia.\nQuesto libro è più interessante.\ncosì economico come · il migliore / il peggiore",
                        'exercicios' => [
                            m('Comparativo correto:', ['più grande della', 'più grande che la', 'grande più di', 'il più che'], 'più grande della'),
                            t('Traduza: più interessante', 'mais interessante'),
                            c('Complete: Non fa così freddo _____ ieri.', 'come'),
                            emp('Una.', [['più grande', 'maior'], ['più economico', 'mais barato'], ['il migliore', 'o melhor'], ['il peggiore', 'o pior']]),
                            vf('"(Così)… come" compara igualdade.', true),
                            ordena('Monte:', 'Questa citta e piu grande della mia'),
                            m('Il migliore é:', ['comparativo', 'superlativo', 'passado', 'futuro'], 'superlativo'),
                            m('Più interessante serve para:', ['comparar qualidade', 'só cores', 'só horas', 'só nomes'], 'comparar qualidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Lavoro e studio',
                'descricao' => 'Profissão, prazos e conselhos.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Al lavoro',
                        'resumo' => 'riunione, scadenza, lavoro come, remoto',
                        'teoria' => "Lavoro come designer / insegnante / infermiere.\nHo una riunione alle dieci.\nLa scadenza è venerdì.\nLavoro da remoto due giorni a settimana.",
                        'exercicios' => [
                            m('"Lavoro come insegnante" diz:', ['a profissão', 'o preço', 'a idade', 'a cor'], 'a profissão'),
                            t('Traduza: Ho una riunione', 'tenho uma reuniao|tenho uma reunião'),
                            c('Complete: La _____ è venerdì. (prazo)', 'scadenza'),
                            emp('Una.', [['riunione', 'reunião'], ['scadenza', 'prazo'], ['da remoto', 'remoto'], ['infermiere', 'enfermeiro']]),
                            vf('"Da remoto" é trabalho à distância.', true),
                            ordena('Monte:', 'Ho una riunione alle dieci'),
                            m('Designer é:', ['uma profissão', 'um país', 'uma refeição', 'um transporte'], 'uma profissão'),
                            m('Due giorni a settimana fala de:', ['frequência', 'preço', 'tamanho', 'cor'], 'frequência'),
                        ],
                    ],
                    [
                        'titulo' => 'Abilità',
                        'resumo' => 'sono bravo, devo, dovresti',
                        'teoria' => "Sono bravo a scrivere.\nSo usare i fogli di calcolo.\nDevo finire questo oggi.\nDovresti mandare l'email adesso.",
                        'exercicios' => [
                            m('"Sono bravo a scrivere" fala de:', ['habilidade', 'fome', 'direção', 'preço'], 'habilidade'),
                            t('Traduza: Dovresti mandare l\'email', 'voce deveria enviar o email|você deveria enviar o e-mail'),
                            c('Complete: Devo _____ questo oggi.', 'finire'),
                            emp('Una.', [['bravo a', 'bom em'], ['devo', 'preciso / devo'], ['dovresti', 'você deveria'], ['so', 'eu sei']]),
                            vf('"Dovresti" dá conselho.', true),
                            ordena('Monte:', "Dovresti mandare l'email adesso"),
                            m('Fogli di calcolo são:', ['planilhas', 'pratos', 'sapatos', 'ruas'], 'planilhas'),
                            m('Devo expressa:', ['necessidade', 'cor', 'lugar', 'só hora'], 'necessidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Se e quando',
                'descricao' => 'Condições reais com se e quando.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Se piove',
                        'resumo' => 'se + presente, futuro',
                        'teoria' => "Se piove, resterò a casa.\nSe finisco presto, ti chiamo.\nA meno che non stia male, vengo.",
                        'exercicios' => [
                            m('Forma correta:', ['Se piove, resterò', 'Se pioverò, resto', 'Se pioggia, resto', 'Se piove, resterò io casa'], 'Se piove, resterò'),
                            t('Traduza: Se finisco presto, ti chiamo', 'se eu terminar cedo te ligo|se terminar cedo eu te ligo'),
                            c('Complete: Se piove, _____ a casa.', 'restero|resterò'),
                            emp('Una.', [['se', 'se'], ['a meno che', 'a menos que'], ['presto', 'cedo'], ['male', 'mal / doente']]),
                            vf('Na condição real, se vai com presente.', true),
                            ordena('Monte:', 'Se finisco presto ti chiamo'),
                            m('A meno che non stia male. é:', ['uma exceção', 'um oi', 'um preço', 'uma cor'], 'uma exceção'),
                            m('Resterò a casa. é:', ['o resultado', 'o passado', 'um substantivo', 'uma cor'], 'o resultado'),
                        ],
                    ],
                    [
                        'titulo' => 'Quando arrivo',
                        'resumo' => 'quando, appena, prima, dopo',
                        'teoria' => "Quando arrivo, ti scrivo.\nAppena lo so, ti dico.\nPrima di uscire, mangiamo.\nDopo la lezione, parliamo.",
                        'exercicios' => [
                            m('Quando arrivo, ti scrivo. fala de:', ['futuro em sequência', 'só passado', 'uma cor', 'um preço'], 'futuro em sequência'),
                            t('Traduza: Appena lo so', 'assim que eu souber|tão logo eu saiba'),
                            c('Complete: _____ di uscire, mangiamo.', 'Prima'),
                            emp('Una.', [['quando', 'quando'], ['appena', 'assim que'], ['prima', 'antes'], ['dopo', 'depois']]),
                            vf('"Appena" indica o momento imediato.', true),
                            ordena('Monte:', 'Quando arrivo ti scrivo'),
                            m('Dopo la lezione é:', ['depois da aula', 'antes da aula', 'no almoço só', 'nunca'], 'depois da aula'),
                            m('Parliamo. aqui é:', ['combinado no presente', 'uma cor', 'um país', 'um número'], 'combinado no presente'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Esperienze',
                'descricao' => 'Passato prossimo com mai / già para o que já viveu.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Sei mai stato…?',
                        'resumo' => 'sei stato, mai, già, ancora',
                        'teoria' => "Sei mai stato a Salvador?\nNon ho mai assaggiato questo.\nNon ho ancora finito.\nHa già fatto la valigia.",
                        'exercicios' => [
                            m('Pergunta de experiência:', ['Sei mai stato a Salvador?', 'Sei Salvador?', 'Hai Salvador?', 'Stato tu Salvador?'], 'Sei mai stato a Salvador?'),
                            t('Traduza: Non ho mai assaggiato questo', 'nunca provei isso|eu nunca experimentei isso'),
                            c('Complete: Non ho _____ finito.', 'ancora'),
                            emp('Una.', [['mai', 'nunca / alguma vez'], ['già', 'já'], ['ancora', 'ainda'], ['assaggiare', 'provar']]),
                            vf('"Non… ancora" significa ainda não.', true),
                            ordena('Monte:', 'Sei mai stato a Salvador'),
                            m('Ha già fatto la valigia. significa:', ['já fez as malas', 'vai viajar ontem', 'não tem mala', 'perdeu o voo'], 'já fez as malas'),
                            m('Mai / già falam de:', ['experiência até agora', 'só uma cor', 'só um preço', 'só um nome'], 'experiência até agora'),
                        ],
                    ],
                    [
                        'titulo' => 'Raccontare',
                        'resumo' => 'è stato, mi sentivo, alla fine',
                        'teoria' => "Era la prima volta.\nAll'inizio ero nervoso, poi mi sono rilassato.\nAlla fine è andato tutto bene.\nLo rifarei.",
                        'exercicios' => [
                            m('Era la prima volta. descreve:', ['experiência nova', 'preço', 'cor', 'endereço'], 'experiência nova'),
                            t('Traduza: Alla fine è andato tutto bene', 'no final deu tudo certo|no fim tudo correu bem'),
                            c("Complete: All'inizio ero _____.", 'nervoso'),
                            emp('Una.', [['prima volta', 'primeira vez'], ['mi sentivo', 'eu me sentia'], ['alla fine', 'no fim'], ['rifarei', 'faria de novo']]),
                            vf('"Lo rifarei" avalia de forma positiva.', true),
                            ordena('Monte:', 'Lo rifarei'),
                            m('Ero nervoso. fala de:', ['emoção', 'tamanho', 'moeda', 'direção'], 'emoção'),
                            m('Poi mi sono rilassato. mostra:', ['mudança na história', 'um preço', 'um oi', 'um número'], 'mudança na história'),
                        ],
                    ],
                ],
            ],
        ],
    ];
}

function niveis_alemao(): array
{
    return [
        'descricao' => 'Lehrpfad A1–A4: von Hallo bis zu Erfahrungen, Meinungen und Plänen.',
        'palavras' => [
            ['Gestern', 'Ontem', 'Gestern habe ich gearbeitet.', 'A2'],
            ['Schon', 'Já', 'Ich habe schon gegessen.', 'A2'],
            ['Weil', 'Porque', 'Ich bin geblieben, weil es geregnet hat.', 'B1'],
            ['Obwohl', 'Embora', 'Obwohl ich müde war, bin ich gegangen.', 'B1'],
            ['Wenn', 'Se / quando', 'Wenn es regnet, bleibe ich zu Hause.', 'B2'],
            ['Erfahrung', 'Experiência', 'Es war eine tolle Erfahrung.', 'B2'],
        ],
        'unidades' => [
            [
                'titulo' => 'Gestern',
                'descricao' => 'Perfekt para contar o que aconteceu.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Perfekt',
                        'resumo' => 'habe gearbeitet, bin gegangen',
                        'teoria' => "Gestern habe ich gearbeitet. Sie ist zum Markt gegangen.\nhaben + Partizip · sein com verbos de movimento\nWas hast du gemacht?",
                        'exercicios' => [
                            m('Qual está no passado?', ['Gestern gehe ich', 'Gestern bin ich gegangen', 'Gestern gehend', 'Gestern geht'], 'Gestern bin ich gegangen'),
                            t('Traduza: Gestern habe ich gearbeitet', 'ontem eu trabalhei|trabalhei ontem'),
                            c('Complete: Sie ist nicht _____. (gegangen)', 'gegangen'),
                            emp('Una.', [['habe gemacht', 'eu fiz'], ['bin gegangen', 'eu fui'], ['hatte', 'tive'], ['war', 'era / estava']]),
                            vf('"Was hast du gemacht?" pergunta o que você fez.', true),
                            ordena('Monte:', 'Was hast du gestern gemacht'),
                            m('Sie sind gegangen. usa:', ['sein no plural', 'só haben', 'futuro', 'imperativo'], 'sein no plural'),
                            m('Pergunta correta:', ['Bist du zum Markt gegangen?', 'Gehst Markt du?', 'Bist Markt?', 'Gegangen du?'], 'Bist du zum Markt gegangen?'),
                        ],
                    ],
                    [
                        'titulo' => 'Den Tag erzählen',
                        'resumo' => 'zuerst, dann, danach, am Ende',
                        'teoria' => "zuerst · dann · danach · am Ende\nAm Morgen… · Am Nachmittag… · Am Abend…\nEs war ein langer Tag.",
                        'exercicios' => [
                            m('Qual organiza a história?', ['zuerst / dann', 'hallo / tschüss', 'links / rechts', 'ja / nein'], 'zuerst / dann'),
                            t('Traduza: Es war ein langer Tag', 'foi um dia longo|foi um longo dia'),
                            c('Complete: _____ bin ich nach Hause gegangen. (depois)', 'Danach|Dann'),
                            emp('Una.', [['Morgen', 'manhã'], ['Nachmittag', 'tarde'], ['Abend', 'noite'], ['am Ende', 'por fim']]),
                            vf('"Am Ende" fecha a sequência.', true),
                            ordena('Monte:', 'Zuerst habe ich gefruhstuckt'),
                            m('Am Abend habe ich geschlafen. descreve:', ['o fim do dia', 'o futuro', 'um pedido', 'uma cor'], 'o fim do dia'),
                            m('Danach significa:', ['antes', 'depois', 'em vez de', 'apesar de'], 'depois'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Pläne',
                'descricao' => 'werden e convites.',
                'nivel' => 'A2',
                'aulas' => [
                    [
                        'titulo' => 'Ich werde…',
                        'resumo' => 'futuro com werden / planos',
                        'teoria' => "Ich werde im Juli reisen.\nSie wird heute Abend lernen.\nKommst du?\nIch habe vor, zu reisen.",
                        'exercicios' => [
                            m('Plano / futuro:', ['Ich werde reisen', 'Ich reisend', 'Ich werde Reise', 'Ich reisen werde ich'], 'Ich werde reisen'),
                            t('Traduza: Ich werde lernen', 'vou estudar|eu vou aprender|vou aprender'),
                            c('Complete: Sie wird heute Abend _____.', 'lernen'),
                            emp('Una.', [['heute Abend', 'hoje à noite'], ['morgen', 'amanhã'], ['nächste Woche', 'semana que vem'], ['im Juli', 'em julho']]),
                            vf('"Kommst du?" pode confirmar um plano.', true),
                            ordena('Monte:', 'Wir werden reisen'),
                            m('Nächste Woche aponta para:', ['passado', 'futuro próximo', 'agora', 'nunca'], 'futuro próximo'),
                            m('Negativa:', ['Ich werde nicht gehen', 'Ich nicht werde', 'Ich no werde', 'Ich werde nein'], 'Ich werde nicht gehen'),
                        ],
                    ],
                    [
                        'titulo' => 'Einladungen',
                        'resumo' => 'Hast du Lust, gern, ich kann nicht',
                        'teoria' => "Hast du Lust auszugehen?\nGerne. / Das würde ich gern.\nTut mir leid, ich kann nicht.\nVielleicht später.",
                        'exercicios' => [
                            m('Convite:', ['Hast du Lust auszugehen?', 'Hast du Preis?', 'Hast du Farbe?', 'Hast du Wie viel?'], 'Hast du Lust auszugehen?'),
                            t('Traduza: Tut mir leid, ich kann nicht', 'desculpa nao posso|sinto muito, não posso'),
                            c('Complete: Das würde ich _____.', 'gern'),
                            emp('Una.', [['gerne', 'com prazer'], ['vielleicht', 'talvez'], ['ich kann nicht', 'não posso'], ['Lust haben', 'ter vontade']]),
                            vf('"Hast du Lust…?" é um convite.', true),
                            ordena('Monte:', 'Hast du Lust auszugehen'),
                            m('Gerne. responde:', ['um convite', 'um preço', 'um nome', 'uma hora'], 'um convite'),
                            m('Vielleicht indica:', ['certeza', 'possibilidade', 'passado', 'ordem'], 'possibilidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Meinungen',
                'descricao' => 'Comparar, concordar e explicar.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Ich finde…',
                        'resumo' => 'ich finde, weil, ich stimme zu',
                        'teoria' => "Ich finde den Film super.\nIch bin (nicht) einverstanden.\nweil · deshalb · meiner Meinung nach",
                        'exercicios' => [
                            m('Começar opinião:', ['Ich finde…', 'Gestern Tisch…', 'Hallo Preis…', 'Links…'], 'Ich finde…'),
                            t('Traduza: Ich bin einverstanden', 'eu concordo|estou de acordo'),
                            c('Complete: Ich bin geblieben, _____ es geregnet hat.', 'weil'),
                            emp('Una.', [['einverstanden', 'de acordo'], ['nicht einverstanden', 'discordo'], ['weil', 'porque'], ['meiner Meinung nach', 'na minha opinião']]),
                            vf('"Ich bin nicht einverstanden" discorda.', true),
                            ordena('Monte:', 'Ich finde den Film super'),
                            m('Deshalb introduz:', ['a consequência', 'um oi', 'um número', 'uma cor'], 'a consequência'),
                            m('Nicht einverstanden significa:', ['concordo', 'discordo', 'não sei', 'espero'], 'discordo'),
                        ],
                    ],
                    [
                        'titulo' => 'Komparativ',
                        'resumo' => 'größer als, so… wie, am besten',
                        'teoria' => "Diese Stadt ist größer als meine.\nDieses Buch ist interessanter.\nso günstig wie · am besten / am schlechtesten",
                        'exercicios' => [
                            m('Comparativo correto:', ['größer als', 'größer wie', 'groß als', 'am größer'], 'größer als'),
                            t('Traduza: interessanter', 'mais interessante'),
                            c('Complete: Es ist nicht so kalt _____ gestern.', 'wie'),
                            emp('Una.', [['größer', 'maior'], ['günstiger', 'mais barato'], ['am besten', 'o melhor'], ['am schlechtesten', 'o pior']]),
                            vf('"So… wie" compara igualdade.', true),
                            ordena('Monte:', 'Diese Stadt ist großer als meine'),
                            m('Am besten é:', ['comparativo', 'superlativo', 'passado', 'futuro'], 'superlativo'),
                            m('Interessanter serve para:', ['comparar qualidade', 'só cores', 'só horas', 'só nomes'], 'comparar qualidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Arbeit und Studium',
                'descricao' => 'Profissão, prazos e conselhos.',
                'nivel' => 'B1',
                'aulas' => [
                    [
                        'titulo' => 'Bei der Arbeit',
                        'resumo' => 'Meeting, Frist, ich arbeite als, remote',
                        'teoria' => "Ich arbeite als Designer / Lehrer / Krankenpfleger.\nIch habe um zehn ein Meeting.\nDie Frist ist Freitag.\nIch arbeite zwei Tage die Woche im Homeoffice.",
                        'exercicios' => [
                            m('"Ich arbeite als Lehrer" diz:', ['a profissão', 'o preço', 'a idade', 'a cor'], 'a profissão'),
                            t('Traduza: Ich habe ein Meeting', 'tenho uma reuniao|tenho uma reunião'),
                            c('Complete: Die _____ ist Freitag. (prazo)', 'Frist'),
                            emp('Una.', [['Meeting', 'reunião'], ['Frist', 'prazo'], ['Homeoffice', 'remoto'], ['Krankenpfleger', 'enfermeiro']]),
                            vf('"Im Homeoffice" é trabalho à distância.', true),
                            ordena('Monte:', 'Ich habe um zehn ein Meeting'),
                            m('Designer é:', ['uma profissão', 'um país', 'uma refeição', 'um transporte'], 'uma profissão'),
                            m('Zwei Tage die Woche fala de:', ['frequência', 'preço', 'tamanho', 'cor'], 'frequência'),
                        ],
                    ],
                    [
                        'titulo' => 'Fähigkeiten',
                        'resumo' => 'gut in, ich muss, du solltest',
                        'teoria' => "Ich bin gut im Schreiben.\nIch kann Tabellenkalkulation.\nIch muss das heute fertig machen.\nDu solltest die E-Mail jetzt senden.",
                        'exercicios' => [
                            m('"Ich bin gut im Schreiben" fala de:', ['habilidade', 'fome', 'direção', 'preço'], 'habilidade'),
                            t('Traduza: Du solltest die E-Mail senden', 'voce deveria enviar o email|você deveria enviar o e-mail'),
                            c('Complete: Ich muss das heute _____ machen.', 'fertig'),
                            emp('Una.', [['gut in', 'bom em'], ['ich muss', 'eu preciso'], ['du solltest', 'você deveria'], ['ich kann', 'eu consigo']]),
                            vf('"Du solltest" dá conselho.', true),
                            ordena('Monte:', 'Du solltest die E-Mail jetzt senden'),
                            m('Tabellenkalkulation é:', ['planilha', 'prato', 'sapato', 'rua'], 'planilha'),
                            m('Ich muss expressa:', ['necessidade', 'cor', 'lugar', 'só hora'], 'necessidade'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Wenn und sobald',
                'descricao' => 'Condições reais com wenn.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Wenn es regnet',
                        'resumo' => 'wenn + Präsens, Futur / Präsens',
                        'teoria' => "Wenn es regnet, bleibe ich zu Hause.\nWenn ich früh fertig bin, rufe ich dich an.\nAußer ich bin krank, komme ich.",
                        'exercicios' => [
                            m('Forma correta:', ['Wenn es regnet, bleibe ich', 'Wenn es wird regnen, bleibe', 'Wenn Regen, bleibe', 'Wenn es regnet, ich bleibe zu'], 'Wenn es regnet, bleibe ich'),
                            t('Traduza: Wenn ich früh fertig bin, rufe ich dich an', 'se eu terminar cedo te ligo|se terminar cedo eu te ligo'),
                            c('Complete: Wenn es regnet, _____ ich zu Hause.', 'bleibe'),
                            emp('Una.', [['wenn', 'se / quando'], ['außer', 'exceto / a menos'], ['früh', 'cedo'], ['krank', 'doente']]),
                            vf('Na condição real, wenn vai com Präsens.', true),
                            ordena('Monte:', 'Wenn ich fruh fertig bin rufe ich dich an'),
                            m('Außer ich bin krank. é:', ['uma exceção', 'um oi', 'um preço', 'uma cor'], 'uma exceção'),
                            m('Bleibe ich zu Hause. é:', ['o resultado', 'o passado', 'um substantivo', 'uma cor'], 'o resultado'),
                        ],
                    ],
                    [
                        'titulo' => 'Sobald ich ankomme',
                        'resumo' => 'sobald, bevor, nachdem',
                        'teoria' => "Sobald ich ankomme, schreibe ich dir.\nBevor wir gehen, essen wir.\nNachdem der Kurs fertig ist, können wir reden.",
                        'exercicios' => [
                            m('Sobald ich ankomme, schreibe ich dir. fala de:', ['futuro em sequência', 'só passado', 'uma cor', 'um preço'], 'futuro em sequência'),
                            t('Traduza: Sobald ich es weiß', 'assim que eu souber|tão logo eu saiba'),
                            c('Complete: _____ wir gehen, essen wir.', 'Bevor'),
                            emp('Una.', [['wenn', 'quando / se'], ['sobald', 'assim que'], ['bevor', 'antes'], ['nachdem', 'depois que']]),
                            vf('"Sobald" indica o momento imediato.', true),
                            ordena('Monte:', 'Sobald ich ankomme schreibe ich dir'),
                            m('Nachdem der Kurs fertig ist é:', ['depois da aula', 'antes da aula', 'no almoço só', 'nunca'], 'depois da aula'),
                            m('Können wir reden. é:', ['possibilidade / convite', 'uma cor', 'um país', 'um número'], 'possibilidade / convite'),
                        ],
                    ],
                ],
            ],
            [
                'titulo' => 'Erfahrungen',
                'descricao' => 'Perfekt com schon / nie para o que já viveu.',
                'nivel' => 'B2',
                'aulas' => [
                    [
                        'titulo' => 'Warst du schon mal…?',
                        'resumo' => 'schon mal, nie, noch nicht',
                        'teoria' => "Warst du schon mal in Salvador?\nIch habe das nie probiert.\nIch bin noch nicht fertig.\nSie hat schon gepackt.",
                        'exercicios' => [
                            m('Pergunta de experiência:', ['Warst du schon mal in Salvador?', 'Bist du Salvador?', 'Hast du Salvador?', 'War Salvador du?'], 'Warst du schon mal in Salvador?'),
                            t('Traduza: Ich habe das nie probiert', 'nunca provei isso|eu nunca experimentei isso'),
                            c('Complete: Ich bin _____ nicht fertig.', 'noch'),
                            emp('Una.', [['schon mal', 'já alguma vez'], ['nie', 'nunca'], ['noch nicht', 'ainda não'], ['probieren', 'provar']]),
                            vf('"Noch nicht" significa ainda não.', true),
                            ordena('Monte:', 'Warst du schon mal in Salvador'),
                            m('Sie hat schon gepackt. significa:', ['já fez as malas', 'vai viajar ontem', 'não tem mala', 'perdeu o voo'], 'já fez as malas'),
                            m('Schon mal / nie falam de:', ['experiência até agora', 'só uma cor', 'só um preço', 'só um nome'], 'experiência até agora'),
                        ],
                    ],
                    [
                        'titulo' => 'Erzählen',
                        'resumo' => 'es war, ich fühlte mich, am Ende',
                        'teoria' => "Es war das erste Mal.\nAm Anfang war ich nervös, dann habe ich mich entspannt.\nAm Ende ist alles gut gelaufen.\nIch würde es wieder machen.",
                        'exercicios' => [
                            m('Es war das erste Mal. descreve:', ['experiência nova', 'preço', 'cor', 'endereço'], 'experiência nova'),
                            t('Traduza: Am Ende ist alles gut gelaufen', 'no final deu tudo certo|no fim tudo correu bem'),
                            c('Complete: Am Anfang war ich _____.', 'nervos|nervös'),
                            emp('Una.', [['erste Mal', 'primeira vez'], ['ich fühlte mich', 'eu me senti'], ['am Ende', 'no fim'], ['wieder', 'de novo']]),
                            vf('"Ich würde es wieder machen" avalia de forma positiva.', true),
                            ordena('Monte:', 'Ich wurde es wieder machen'),
                            m('Ich war nervös. fala de:', ['emoção', 'tamanho', 'moeda', 'direção'], 'emoção'),
                            m('Dann habe ich mich entspannt. mostra:', ['mudança na história', 'um preço', 'um oi', 'um número'], 'mudança na história'),
                        ],
                    ],
                ],
            ],
        ],
    ];
}
